spring:
  batch:
    # job:
    # enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug

retention-policy:
  database:
    name: shard1
    default_configs:
      id_column_name: id
      timestamp_column_name: created_ts
      timestamp_data_type: timestamp
      retention_period_in_days: 3
      batch_size: 2
      sleep_between_delete_batch_in_ms: 100
    tables:
      - schema_name: public
        table_name: table1
        id_column_name: id
        timestamp_column_name: created_at
        timestamp_data_type: timestamp
        retention_period_in_days: 30
      - schema_name: public
        table_name: table2
        id_column_name: id
        timestamp_column_name: created_at
        timestamp_data_type: timestamp
        retention_period_in_days: 6
        batch_size: 10
        sleep_between_delete_batch_in_ms: 10000
